plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

def modId = project.mod_id

group = project.mod_group
version = project.mod_version

base {
    archivesName = modId
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
    withSourcesJar()
}

sourceSets {
    main {
        resources {
            srcDir 'src/generated/resources'
        }
    }
}

minecraft {
    mappings channel: project.mappings_channel, version: project.mappings_version
    copyIdeResources = true

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                "${modId}" {
                    source sourceSets.main
                }
            }
        }

        client {
        }

        server {
            property 'forge.enabledGameTestNamespaces', modId
        }

        gameTest {
            property 'forge.enabledGameTestNamespaces', modId
        }

        data {
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            args '--mod', modId, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}
repositories {
    mavenCentral()
    maven { url = 'https://maven.minecraftforge.net' }
}

dependencies {
    minecraft "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"
}

tasks.withType(ProcessResources).configureEach {
    inputs.property 'modId', modId
    inputs.property 'modVersion', project.mod_version
    inputs.property 'modName', project.mod_name
    inputs.property 'modAuthors', project.mod_authors
    inputs.property 'modLicense', project.mod_license
    inputs.property 'modDescription', project.mod_description
    filteringCharset = 'UTF-8'

    filesMatching('META-INF/mods.toml') {
        expand ([
            'mod_id': modId,
            'mod_version': project.mod_version,
            'mod_name': project.mod_name,
            'mod_authors': project.mod_authors,
            'mod_license': project.mod_license,
            'mod_description': project.mod_description
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(Javadoc).configureEach {
    options.encoding = 'UTF-8'
}

jar {
    manifest {
        attributes(
            'Specification-Title': project.mod_name,
            'Specification-Vendor': project.mod_authors,
            'Specification-Version': project.mod_version,
            'Implementation-Title': project.name,
            'Implementation-Version': project.mod_version,
            'Implementation-Vendor': project.mod_authors
        )
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
            artifact sourcesJar
        }
    }
    repositories {
        mavenLocal()
    }
}
